### ISSUE TITLE
Job listing page. [#123]

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#134]
**Task, 2 hours**
[User story #123]
Related to task #138, #139 (User story #128)
From the header a link can be clicked to visit a page that will generate all the possible job offers from the database. The users will only have access to this list and wont have the authority to post any job offers on behalf of companies.

**Comment by kjanei** [comment]
@BarsemianGeorgik Given what was discussed in the meeting with the manager, it is necessary that we also implement the ability to see the job's description on the site rather than having a link that refers to external sites. This would be best done by having a job-description page specific to each job that contains the company, date, title, description, etc.

**Comment by kjanei** [comment]
This functionality has been implemented; therefore, this task can be closed.
