### ISSUE TITLE
Back-end user profile functionality. 

### ISSUE THREAD

**Issue by dfeokti** [Software-Process/Software-Process.github.io#87]
**Story points: 6,
Priority: Medium,
Risk: Medium**

The user will be able to view their profile, change personal information, password or icon, as well as view submitted questions and accumulated points. 

- [x] Support for modifying various information in the profile, such as
personal information and password. 5 hours. [#97]
- [x] Ability to upload custom images to use as profile pictures. 5 hours. [#98]
[Note: Partially implemented - user can select profile picture from a predefined list, but cannot upload an image of their own choosing.]

- [x] Ability to reference a list of previous submissions, and points. 3 hours [#99]

**Comment by PWatine** [comment]
Test case done for this issue.

**Comment by PWatine** [comment]
![87](https://user-images.githubusercontent.com/35372462/37132556-311ac54a-225c-11e8-9cde-466e5679fc11.png)
Test completed.

**Comment by dfeokti** [comment]
Tests passed, user icons issue to be reopened in Sprint 4.

**Comment by kjanei** [comment]
Although this user story requires that the user be allowed to upload a profile picture of their choosing, this feature has been put back onto the product backlog due to insufficient time.
The website currently has a partial implementation of this requirement, in that the user is able to select a profile picture from among 5 predefined profile pictures. 
Therefore, this user story will be closed, its full implementation to be completed at a later date.
